language: android

android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26

  license:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+